### ISSUE TITLE
QR code improvements for Kin wallet backup/restore

### ISSUE THREAD

**Issue by rorymc** [kinecosystem/kin-ios#1]
details filed in this issue for the old SDK:
* [kinecosystem/kin-sdk-android#78](https://github.com/kinecosystem/kin-sdk-android/issues/78)
* Enhancement filed in new Android SDK [kinecosystem/kin-android#4](https://github.com/kinecosystem/kin-android/issues/4)

tl;dr
* wallet restore uses a QR code
* users occasionally screenshot the QR code, and it has all the info encoded, but restore process does not allow a screenshot to be used

would be great to add this into the new SDKs

**Comment by chaseeb** [comment]
base-compat will deprecated but this functionality will be added to kin-base in the future.
