### ISSUE TITLE
App crashes with error in XDRCodableExtensions.swift.

### ISSUE THREAD

**Issue by devayansarkar** [kinecosystem/kin-ios#13]
Hi Team, 

Our app works fine in the simulator but crashes when we attempt a transaction operation. We are on the latest version and the crash log suggests it is crashing during a process in XDRCodableExtensions.swift.

I am attaching the crash logs. Have you heard of similar issues from other teams ?

Best regards,
Dev
[testflight_feedback.zip](https://github.com/kinecosystem/kin-ios/files/6031820/testflight_feedback.zip)

**Comment by samdowd** [comment]
This should be fixed in the most recent version, closing. If you see this crash again in v2.1.1+, please reopen, and I'll fix it.
