### ISSUE TITLE
Crash when load transaction history

### ISSUE THREAD

**Issue by siliconprime-manhnguyen** [kinecosystem/kin-ios#15]
<img width="1680" alt="crash" src="https://user-images.githubusercontent.com/42996953/116521362-11e03d00-a8fe-11eb-8580-d163b8289b39.png">

Hi support Team,
We are on the latest version(0.4.5). We have encountered the crash when we load kin transaction history

Step 1: We create a transaction with a unique memo added
Step 2: We try to read transaction history and crashes
Step 3: Even after re-opening the app which crashes, any attempt to read transaction history crashes the app again

**Comment by hitwill** [comment]
@siliconprime-manhnguyen Does this happen only when you send two transactions with the same memo?

**Comment by siliconprime-manhnguyen** [comment]
@hitwill No . My memo always unit It's combine userId with current timestamp
