### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by l-hendriks** [kinecosystem/kin-ios#2]
For the compat case, you also need to remove the BackupRestore subspec. It still works without it, might want to add this :) great work!

So I had to update:

```
pod 'KinSDK', '~> 1.0.2', :subspecs => ['BackupRestore']
```

To 

```
  pod 'KinBaseCompat', '~> 0.1.0'
```

**Comment by kikengineering** [comment]
Good point, backup and restore is part of KinBaseCompat now. Thanks for your suggestion, I'll include it in the readme.

**Comment by kikengineering** [comment]
Added to KinBaseCompat/README on 0.1.1
