### ISSUE TITLE
Cannot send transaction

### ISSUE THREAD

**Issue by l-hendriks** [kinecosystem/kin-ios#3]
I get the following error after installing the compat SDK:

```
Error send transaction
with error: retriesExceeded
```

**Comment by kikengineering** [comment]
Ah, it looks like the retry strategy isn't surfacing the underlying error. I'll address it in the coming release. If this is a sequence number issue, maybe you can try calling `status()` on `KinAccount` before sending the transaction.

**Comment by kikengineering** [comment]
Just made a `0.1.1` release that changes some error handling logic, it should at least let you know what error is happening.

**Comment by l-hendriks** [comment]
It "was not enough fee" (I had a fee of "1", but now it should be "100" I guess?). After changing the fee to 100 is works!

I'll leave the issue open, feel free to close (maybe you want to update a readme or something)

**Comment by kikengineering** [comment]
If you leave the fee nil, the old(and the current compat) sdk would set a default fee of 100. I'm not sure how a fee of 1 worked. Anyway good to hear that it works for you now and thanks for your feedback.
