### ISSUE TITLE
kin balance does not update with KinBaseCompat

### ISSUE THREAD

**Issue by rorymc** [kinecosystem/kin-ios#5]
after integrating the new kin-ios sdk (‘KinBaseCompat’, ‘~ > 0.1.0’), the real-time call-back when kin balance change is not working now.

The function get balance was still working normally with the old ios SDK:
```
private func watchBalance(completion : @escaping ((Kin)- > Void)) {
        if let account = self.getFirstAccount() {
            self.watch = try? account.watchBalance(nil)
            self.watch?.emitter.on(queue: .main, next: { [weak self] balance in
                self?.currentKin = balance
                completion(balance)
            })
            .add(to: self.linkBag)
        }
    }
    
    func getFirstAccount() - > KinAccount? {
        if let kinClient = kinClient {
            return kinClient.accounts.first
        }
        return nil
    }
```

issue confirmed in:
* 0.1.0
* 0.1.1

**Comment by kikengineering** [comment]
Thanks for surfacing this issue. I just put up a new release 0.1.2 that addresses this issue. Let me know if it works for you.

**Comment by rorymc** [comment]
fyi, this should be fixed as part of:

- https://github.com/kinecosystem/kin-ios/releases/tag/0.1.2

**Comment by rorymc** [comment]
fyi @kikengineering , we've integrated 0.1.2 and tested this -- resolves the iOS balance issues !

thank you so much for the quick help.  I'll also let other Kin apps know in our shared slack.
