### ISSUE TITLE
kin backup page has text which is cut off in iOS 13 (okay in iOS 12)

### ISSUE THREAD

**Issue by rorymc** [kinecosystem/kin-ios#6]
in the backup-and-restore flow, the text above the QR code is being cut off, but oddly only in iOS 13 (was fine in iOS 12)

See attached screenshot:
![example-cut-off-text-in-kin-backup](https://user-images.githubusercontent.com/3675696/86870978-3d9fe700-c08e-11ea-9719-eb8e2d0ed994.jpg)

**Comment by rorymc** [comment]
my misunderstanding -- turns out this already existed as a bug in the old iOS library, so this is not new.

That being said, would be nice if the iOS users could read the text while creating a backup QR code.

**Comment by kikengineering** [comment]
Thanks for letting us know. You are right that this is an existing issue from the old sdk. 

It's an issue with presenting the backup flow modally onto a view controller. There's a major change in how modal presentation works on iOS 13 that the old sdk didn't account for.
```
// This is probably the call you're using to present it modally.
func backup(_ kinAccount: KinAccount, presentedOnto viewController: UIViewController) -> Bool
```

We will address this issue in the MS2 release timeframe. In the meantime, if pushing onto a navigation controller makes sense in your UI flow, you can use this method instead:
```
func backup(_ kinAccount: KinAccount, pushedOnto navigationController: UINavigationController) -> Bool
```

**Comment by chaseeb** [comment]
base-compat will be deprecated, but will be providing functionality in the future for use with kin-base
