### ISSUE TITLE
Kin backup with no configured mail client means you cannot finish the backup process

### ISSUE THREAD

**Issue by l-hendriks** [kinecosystem/kin-ios#8]
If you don't have a configured mail client, you will get an error message and you cannot continue. Instead of requiring a mail client (which many people don't have) I think it is better to just open the share dialog. People can share via email there, or choose any other method they like to save that image.

**Comment by rorymc** [comment]
fyi, if users were able to screenshot the backup QR code, and then restore with the screenshot (since all the data is contained within a reasonably high fidelity screenshot), then it may solve this issue.

ref:  https://github.com/kinecosystem/kin-ios/issues/1

**Comment by chaseeb** [comment]
base-compat will be deprecated but we will be providing functionality for encoding/decoding for  kin-base in the future
